#!/usr/bin/env python3
"""
Lazy strategy-memory loader for live trading decisions.

Reads strategy_memory.json produced by strategy_learner.py.
"""

import json
import logging
from pathlib import Path

from policy_artifacts import policy_artifacts_enabled

logger = logging.getLogger(__name__)

BASE_DIR = Path(__file__).resolve().parent
MEMORY_FILE = BASE_DIR / "strategy_memory.json"

_strategy_memory = {}
_strategy_memory_mtime = 0.0


def _load_strategy_memory():
    global _strategy_memory, _strategy_memory_mtime

    if not policy_artifacts_enabled():
        return {}

    if not MEMORY_FILE.exists():
        return {}

    try:
        mtime = MEMORY_FILE.stat().st_mtime
        if mtime <= _strategy_memory_mtime:
            return _strategy_memory

        _strategy_memory = json.loads(MEMORY_FILE.read_text())
        _strategy_memory_mtime = mtime

        logger.info(
            "Strategy memory loaded: "
            f"trade_count={_strategy_memory.get('trade_count')} "
            f"generated_at={_strategy_memory.get('generated_at')}"
        )

    except Exception as e:
        logger.error(f"Failed to load strategy memory: {e}")
        _strategy_memory = {}

    return _strategy_memory


def memory_for_signal(symbol, setup_quality=None):
    """
    Return live memory adjustment for a symbol/setup.

    Output is intentionally simple:
    {
      "available": bool,
      "recommendation": "favor|neutral|caution|avoid|observe",
      "min_setup_score": int,
      "reason": str,
      "symbol_memory": {...}
    }
    """
    mem = _load_strategy_memory()
    if not mem:
        return {
            "available": False,
            "recommendation": "none",
            "min_setup_score": None,
            "reason": (
                "policy artifacts disabled"
                if not policy_artifacts_enabled()
                else "strategy_memory.json unavailable"
            ),
        }

    symbol = (symbol or "").upper()
    symbols = mem.get("symbols") or {}
    symbol_mem = symbols.get(symbol)

    if not symbol_mem:
        return {
            "available": True,
            "recommendation": "observe",
            "min_setup_score": None,
            "reason": f"no symbol memory for {symbol}",
        }

    rec = symbol_mem.get("recommendation", "observe")
    min_score = symbol_mem.get("min_setup_score")

    return {
        "available": True,
        "recommendation": rec,
        "min_setup_score": min_score,
        "reason": symbol_mem.get("reason"),
        "symbol_memory": symbol_mem,
        "generated_at": mem.get("generated_at"),
        "lookback_days": mem.get("lookback_days"),
    }

def get_strategy_memory():
    """Public accessor for the full strategy memory document."""
    return _load_strategy_memory()


def contextual_memory_for_signal(symbol, intelligence_context=None):
    """
    Return symbol + contextual learned memory for the current signal.

    Uses sections generated by strategy_learner.py:
    - symbols
    - setup_label_context
    - prediction_decision_context
    - buy_opportunity_context
    - session_trend_context
    - symbol_setup_label_context
    - symbol_prediction_context
    - symbol_buy_opportunity_context
    - symbol_session_trend_context
    """
    mem = _load_strategy_memory()
    if not mem:
        return {
            "available": False,
            "reason": (
                "policy artifacts disabled"
                if not policy_artifacts_enabled()
                else "strategy_memory.json unavailable"
            ),
            "matches": [],
        }

    symbol = (symbol or "").upper()
    ctx = intelligence_context or {}

    setup = ctx.get("setup") or {}
    prediction = ctx.get("prediction") or {}
    buy_opp = ctx.get("buy_opportunity") or {}
    session = ctx.get("session_momentum") or {}

    setup_label = setup.get("setup_label") or "unknown"
    prediction_decision = prediction.get("prediction_decision") or "unknown"
    buy_opp_rec = buy_opp.get("buy_opportunity_recommendation") or "unknown"
    session_label = session.get("trend_label") or "unknown"

    lookups = [
        ("symbol", "symbols", symbol),
        ("setup_label", "setup_label_context", setup_label),
        ("prediction_decision", "prediction_decision_context", prediction_decision),
        ("buy_opportunity", "buy_opportunity_context", buy_opp_rec),
        ("session_trend", "session_trend_context", session_label),
        ("symbol_setup_label", "symbol_setup_label_context", f"{symbol}|{setup_label}"),
        ("symbol_prediction", "symbol_prediction_context", f"{symbol}|{prediction_decision}"),
        ("symbol_buy_opportunity", "symbol_buy_opportunity_context", f"{symbol}|{buy_opp_rec}"),
        ("symbol_session_trend", "symbol_session_trend_context", f"{symbol}|{session_label}"),
    ]

    matches = []
    for label, section, key in lookups:
        data = (mem.get(section) or {}).get(key)
        if data:
            matches.append({
                "label": label,
                "section": section,
                "key": key,
                "recommendation": data.get("recommendation"),
                "min_setup_score": data.get("min_setup_score"),
                "expectancy": data.get("expectancy"),
                "win_rate_pct": data.get("win_rate_pct"),
                "trades": data.get("trades"),
                "reason": data.get("reason"),
                "manual_override": data.get("manual_override", False),
            })

    return {
        "available": True,
        "generated_at": mem.get("generated_at"),
        "lookback_days": mem.get("lookback_days"),
        "matches": matches,
    }
