"""Advanced-alpha feature definitions."""

from __future__ import annotations

from .registry_types import FeatureSpec

ADVANCED_ALPHA_V1_FEATURES: tuple[FeatureSpec, ...] = (
    FeatureSpec(
        name="cumulative_volume_delta",
        dtype="float",
        nullable=True,
        default=None,
        runtime_source="bar_pattern_features.cumulative_volume_delta",
        offline_source="bar_pattern_features.cumulative_volume_delta",
        point_in_time_cutoff="bar_interval_close <= decision_time",
        staleness_rule="same session cumulative state",
        semantic_version="advanced_alpha_v1",
        authority_eligibility="paper_only_after_lifecycle",
    ),
    FeatureSpec(
        name="fractional_diff_zscore_20",
        dtype="float",
        nullable=True,
        default=None,
        runtime_source="bar_pattern_features.fractional_diff_zscore_20",
        offline_source="bar_pattern_features.fractional_diff_zscore_20",
        point_in_time_cutoff="bar_interval_close <= decision_time",
        staleness_rule="rolling window available and not stale",
        semantic_version="advanced_alpha_v1",
        authority_eligibility="paper_only_after_lifecycle",
    ),
    FeatureSpec(
        name="liquidity_stress_indicator",
        dtype="float",
        nullable=True,
        default=None,
        runtime_source="sizing_policy/liquidity stress context",
        offline_source="execution_quality plus bar order-flow proxy features",
        point_in_time_cutoff="decision_time_or_earlier",
        staleness_rule="execution quality snapshot not stale",
        semantic_version="advanced_alpha_v1",
        authority_eligibility="size_down_only_after_lifecycle",
    ),
    FeatureSpec(
        name="spacex_value_chain_relationship_weight",
        dtype="float",
        nullable=True,
        default=None,
        runtime_source="spacex_value_chain_graph.relationship_weight",
        offline_source="spacex_value_chain_graph.relationship_weight",
        point_in_time_cutoff="symbol_universe_snapshot <= decision_time",
        staleness_rule="symbol universe version must match decision snapshot",
        semantic_version="advanced_alpha_v1",
        authority_eligibility="paper_context_only_no_standalone_authority",
    ),
    FeatureSpec(
        name="spacex_value_chain_information_shock_score",
        dtype="float",
        nullable=True,
        default=None,
        runtime_source="spacex_value_chain_graph.lead_lag_shock.information_shock_score",
        offline_source="aligned catalyst/cohort return windows",
        point_in_time_cutoff="all returns timestamps <= decision_time",
        staleness_rule="aligned return window must be current for active session",
        semantic_version="advanced_alpha_v1",
        authority_eligibility="paper_context_only_no_standalone_authority",
    ),
    FeatureSpec(
        name="spacex_value_chain_liquidity_siphon_ratio",
        dtype="float",
        nullable=True,
        default=None,
        runtime_source="spacex_value_chain_graph.index_inflow_vs_basket_outflow",
        offline_source="catalyst index/basket flow research snapshots",
        point_in_time_cutoff="flow snapshot timestamps <= decision_time",
        staleness_rule="flow snapshot must be same session and not stale",
        semantic_version="advanced_alpha_v1",
        authority_eligibility="paper_context_only_no_standalone_authority",
    ),
)
