"""Observe-only historical-bar model intelligence summary.

This service reads candidate diagnostics generated by
``pipeline/train_historical_bar_model.py`` and returns a compact payload for
canonical intelligence snapshots and operator reports. It does not load model
binaries, score symbols, size positions, block trades, or submit orders.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ml_platform.config import MODEL_ROOT

HISTORICAL_BAR_MODEL_INTELLIGENCE_VERSION = "historical_bar_model_intelligence_v1"
DEFAULT_CANDIDATE_DIR = MODEL_ROOT / "historical_bar_patterns_v1" / "candidates"


def _read_json(path: Path) -> dict[str, Any] | None:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def _diagnostics(candidate_dir: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for path in sorted(candidate_dir.glob("historical_bar_*_*.diagnostic.json")):
        payload = _read_json(path)
        if not payload:
            continue
        payload["_diagnostic_path"] = str(path)
        rows.append(payload)
    return rows


def _latest_by_label(rows: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    latest: dict[str, dict[str, Any]] = {}
    for row in rows:
        label = str(row.get("label_target") or "unknown")
        current = latest.get(label)
        if current is None or str(row.get("generated_at") or "") > str(
            current.get("generated_at") or ""
        ):
            latest[label] = row
    return latest


def _float(value: Any) -> float | None:
    try:
        if value is None:
            return None
        return float(value)
    except Exception:
        return None


def _int(value: Any) -> int:
    try:
        return int(value or 0)
    except Exception:
        return 0


def _symbol_gate_rows(
    row: dict[str, Any],
    *,
    min_symbol_accuracy: float,
    toxicity_block_threshold: float,
    max_rows: int = 20,
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    raw = row.get("symbol_metrics") or row.get("per_symbol_metrics") or {}
    if not isinstance(raw, dict) or not raw:
        return [], {
            "status": "insufficient_symbol_metrics",
            "blocked_count": 0,
            "allowed_count": 0,
            "reason": "diagnostic does not expose per-symbol accuracy/toxicity metrics",
        }
    rows: list[dict[str, Any]] = []
    for symbol, metrics in raw.items():
        if not isinstance(metrics, dict):
            continue
        accuracy = _float(metrics.get("accuracy"))
        toxicity = _float(
            metrics.get("vpin_toxicity_20")
            or metrics.get("vpin_toxicity")
            or metrics.get("toxicity")
        )
        blockers: list[str] = []
        if accuracy is None:
            blockers.append("symbol_accuracy_missing")
        elif accuracy < min_symbol_accuracy:
            blockers.append(f"symbol_accuracy:{accuracy:.4f}<{min_symbol_accuracy:.4f}")
        if toxicity is not None and toxicity >= toxicity_block_threshold:
            blockers.append(f"vpin_toxicity:{toxicity:.4f}>={toxicity_block_threshold:.4f}")
        rows.append(
            {
                "symbol": str(symbol).upper(),
                "accuracy": round(accuracy, 4) if accuracy is not None else None,
                "vpin_toxicity": round(toxicity, 4) if toxicity is not None else None,
                "authority_status": "paper_gate_allowed" if not blockers else "blocked",
                "blockers": blockers,
            }
        )
    rows.sort(key=lambda item: (item["authority_status"], item["symbol"]))
    blocked = [item for item in rows if item["authority_status"] == "blocked"]
    allowed = [item for item in rows if item["authority_status"] != "blocked"]
    return rows[:max_rows], {
        "status": "measured",
        "blocked_count": len(blocked),
        "allowed_count": len(allowed),
        "min_symbol_accuracy": min_symbol_accuracy,
        "toxicity_block_threshold": toxicity_block_threshold,
    }


def _assess_label(
    row: dict[str, Any],
    *,
    min_rows: int,
    min_symbols: int,
    min_accuracy: float,
    min_symbol_accuracy: float,
    toxicity_block_threshold: float,
) -> dict[str, Any]:
    training = row.get("training") or {}
    rows_loaded = _int(row.get("rows_loaded"))
    symbol_count = _int(row.get("symbol_count"))
    accuracy = _float(training.get("accuracy"))
    failed: list[str] = []
    if row.get("runtime_effect") != "observe_only_no_live_authority":
        failed.append("runtime_effect_not_observe_only")
    if not training.get("trained"):
        failed.append("not_trained")
    if rows_loaded < min_rows:
        failed.append(f"rows_loaded:{rows_loaded}<{min_rows}")
    if symbol_count < min_symbols:
        failed.append(f"symbol_count:{symbol_count}<{min_symbols}")
    if accuracy is None:
        failed.append("accuracy_missing")
    elif accuracy < min_accuracy:
        failed.append(f"accuracy:{accuracy:.4f}<{min_accuracy:.4f}")

    label_counts = row.get("label_counts") or {}
    positive_count = _int(label_counts.get("1"))
    negative_count = _int(label_counts.get("-1"))
    total_labeled = sum(_int(value) for value in label_counts.values())
    positive_label_rate = round(positive_count / total_labeled, 4) if total_labeled else None
    negative_label_rate = round(negative_count / total_labeled, 4) if total_labeled else None
    symbol_gates, symbol_gate_summary = _symbol_gate_rows(
        row,
        min_symbol_accuracy=min_symbol_accuracy,
        toxicity_block_threshold=toxicity_block_threshold,
    )
    return {
        "label_target": str(row.get("label_target") or "unknown"),
        "model_id": str(row.get("model_id") or "unknown"),
        "status": "observe_only_candidate_ready" if not failed else "not_ready",
        "runtime_effect": str(row.get("runtime_effect") or "unknown"),
        "rows_loaded": rows_loaded,
        "symbol_count": symbol_count,
        "accuracy": None if accuracy is None else round(accuracy, 4),
        "sample_size": _int(training.get("sample_size")),
        "provider": training.get("provider"),
        "generated_at": row.get("generated_at"),
        "diagnostic_path": row.get("_diagnostic_path"),
        "label_counts": label_counts,
        "positive_label_rate": positive_label_rate,
        "negative_label_rate": negative_label_rate,
        "failed_thresholds": failed,
        "artifact_registered_for_live_authority": False,
        "symbol_gate_summary": symbol_gate_summary,
        "symbol_gates": symbol_gates,
    }


def build_historical_bar_model_intelligence(
    *,
    candidate_dir: Path | None = None,
    min_rows: int = 5000,
    min_symbols: int = 20,
    min_accuracy: float = 0.50,
    min_symbol_accuracy: float = 0.60,
    toxicity_block_threshold: float = 0.70,
    max_labels: int = 4,
) -> dict[str, Any]:
    """Return compact observe-only model readiness evidence."""
    candidate_dir = candidate_dir or DEFAULT_CANDIDATE_DIR
    rows = _diagnostics(candidate_dir)
    latest = _latest_by_label(rows)
    labels = [
        _assess_label(
            row,
            min_rows=min_rows,
            min_symbols=min_symbols,
            min_accuracy=min_accuracy,
            min_symbol_accuracy=min_symbol_accuracy,
            toxicity_block_threshold=toxicity_block_threshold,
        )
        for row in latest.values()
    ]
    labels.sort(key=lambda item: str(item.get("label_target") or ""))
    ready = [item for item in labels if item.get("status") == "observe_only_candidate_ready"]
    accuracies = [float(item["accuracy"]) for item in labels if item.get("accuracy") is not None]
    if not labels:
        status = "no_candidates"
    elif len(ready) == len(labels):
        status = "observe_only_ready"
    elif ready:
        status = "partially_ready"
    else:
        status = "not_ready"

    return {
        "version": HISTORICAL_BAR_MODEL_INTELLIGENCE_VERSION,
        "runtime_effect": "observe_only_no_live_authority",
        "authority": "observe_only_report_only_no_order_sizing_or_gate_authority",
        "status": status,
        "candidate_dir": str(candidate_dir),
        "diagnostics_found": len(rows),
        "labels_assessed": len(labels),
        "ready_label_count": len(ready),
        "label_targets": [str(item.get("label_target")) for item in labels[:max_labels]],
        "latest_generated_at": max(
            (str(item.get("generated_at") or "") for item in labels),
            default=None,
        ),
        "accuracy_min": round(min(accuracies), 4) if accuracies else None,
        "accuracy_max": round(max(accuracies), 4) if accuracies else None,
        "thresholds": {
            "min_rows": min_rows,
            "min_symbols": min_symbols,
            "min_accuracy": min_accuracy,
            "min_symbol_accuracy": min_symbol_accuracy,
            "toxicity_block_threshold": toxicity_block_threshold,
        },
        "labels": labels[:max_labels],
        "guardrails": {
            "loads_model_binaries": False,
            "can_block_trades": False,
            "can_size_orders": False,
            "can_submit_orders": False,
            "requires_explicit_authority_wiring_for_runtime_use": True,
        },
    }
